# pod-host.yaml
apiVersion: v1
kind: Pod
metadata:
  name: poc-host-access-pod
spec:
  # ITEM VULNERAVEL: Compartilhar o namespace de rede do host
  hostNetwork: true
  containers:
  - name: sensitive-access
    image: busybox:latest
    command: [ "sh", "-c", "sleep 3600" ]
    volumeMounts:
    - name: host-root-mount
      mountPath: /mnt/host
  volumes:
  - name: host-root-mount
    hostPath:
      # ITEM VULNERAVEL: Montar o diretorio raiz do host
      path: / 
      type: Directory
